Revert "Switch from end of life Apache commons httpclient to Apache httpcomponents httpclient"
This reverts commit 5a061e2cc33ac11e295b6cd3f8e06dbdbeddbe5c.

It's not possible to start the swarm client with the new HTTP library:

$ java -jar ./client/target/swarm-client-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethod
          at java.lang.Class.getDeclaredMethods0(Native Method)
          at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
          at java.lang.Class.getMethod0(Class.java:2774)
          at java.lang.Class.getMethod(Class.java:1663)
          at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
          at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.HttpMethod
       at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
       ... 6 more

Conflicts:
	client/pom.xml